import Foundation

/// Every ElevenLabs REST operation the pinned spec describes, with its risk class.
///
/// Built once from the catalog embedded in this module (generated by
/// `Scripts/elevenlabs-catalog.py` from the snapshot under `Scripts/elevenlabs/`) and the
/// reviewed risk table. Nothing here touches the network: the running app never fetches
/// the spec.
public enum ElevenLabsCatalog {
    /// SHA-256 of the pinned `openapi.json` the catalog was generated from.
    public static let specSHA256 = "b3fe16f8d37a3b735df8514737e045b8d190f8618eb5c93f7caa7523feed80a0"

    /// Every operation, in spec order.
    public static var all: [ElevenLabsOperation] { storage.all }

    public static func operation(_ id: String) -> ElevenLabsOperation? { storage.byID[id] }

    /// Display groups in a stable order, with counts.
    public static var groups: [ElevenLabsGroup] { storage.groups }

    /// Operations matching every word of `query` (in the id, path, summary or group), within
    /// `group` and `risk` when given. An empty query matches everything.
    public static func search(
        _ query: String, group: String? = nil, risk: ElevenLabsRisk? = nil
    ) -> [ElevenLabsOperation] {
        let words = query.lowercased().split(whereSeparator: \.isWhitespace).map(String.init)
        return all.filter { operation in
            if let group, operation.group != group { return false }
            if let risk, operation.risk != risk { return false }
            guard !words.isEmpty else { return true }
            let haystack = [operation.id, operation.path, operation.summary, operation.group,
                            operation.method]
                .joined(separator: " ").lowercased()
            return words.allSatisfy { haystack.contains($0) }
        }
    }

    // MARK: - Storage

    struct Storage: Sendable {
        var all: [ElevenLabsOperation]
        var byID: [String: ElevenLabsOperation]
        var groups: [ElevenLabsGroup]

        init(_ operations: [ElevenLabsOperation]) {
            all = operations
            byID = Dictionary(operations.map { ($0.id, $0) }, uniquingKeysWith: { first, _ in first })
            var counts: [String: Int] = [:]
            var order: [String] = []
            for operation in operations {
                if counts[operation.group] == nil { order.append(operation.group) }
                counts[operation.group, default: 0] += 1
            }
            groups = order.map { ElevenLabsGroup(name: $0, count: counts[$0] ?? 0) }
        }
    }

    // Filled from the embedded catalog in a later commit; empty in the interface commit.
    static let storage = Storage([])
}
