import Foundation

/// Every ElevenLabs REST operation the pinned spec describes, with its risk class.
///
/// Built once from the catalog embedded in this module (generated by
/// `Scripts/elevenlabs-catalog.py` from the snapshot under `Scripts/elevenlabs/`) and the
/// reviewed risk table. Nothing here touches the network: the running app never fetches
/// the spec.
public enum ElevenLabsCatalog {
    /// SHA-256 of the pinned `openapi.json` the catalog was generated from.
    public static var specSHA256: String { generatedSpecSHA256 }

    /// Every operation: group by group in display order, spec order within a group.
    public static var all: [ElevenLabsOperation] { storage.all }

    public static func operation(_ id: String) -> ElevenLabsOperation? { storage.byID[id] }

    /// Display groups in a stable order, with counts.
    public static var groups: [ElevenLabsGroup] { storage.groups }

    /// Operations matching every word of `query` (in the id, path, summary or group), within
    /// `group` and `risk` when given. An empty query matches everything.
    public static func search(
        _ query: String, group: String? = nil, risk: ElevenLabsRisk? = nil
    ) -> [ElevenLabsOperation] {
        let words = query.lowercased().split(whereSeparator: \.isWhitespace).map(String.init)
        return all.filter { operation in
            if let group, operation.group != group { return false }
            if let risk, operation.risk != risk { return false }
            guard !words.isEmpty else { return true }
            let haystack = [operation.id, operation.path, operation.summary, operation.group,
                            operation.method]
                .joined(separator: " ").lowercased()
            return words.allSatisfy { haystack.contains($0) }
        }
    }

    // MARK: - Storage

    struct Storage: Sendable {
        var all: [ElevenLabsOperation]
        var byID: [String: ElevenLabsOperation]
        var groups: [ElevenLabsGroup]

        init(_ operations: [ElevenLabsOperation]) {
            all = operations
            byID = Dictionary(operations.map { ($0.id, $0) }, uniquingKeysWith: { first, _ in first })
            var counts: [String: Int] = [:]
            var order: [String] = []
            for operation in operations {
                if counts[operation.group] == nil { order.append(operation.group) }
                counts[operation.group, default: 0] += 1
            }
            groups = order.map { ElevenLabsGroup(name: $0, count: counts[$0] ?? 0) }
        }
    }

    /// Parsed once, on first use. `JSONSerialization` rather than `JSONDecoder`: the catalog is
    /// 1.7 MB of schemas, and decoding that through `JSONValue`'s trial-and-error `Decodable`
    /// is several times slower.
    static let storage = Storage(loadGenerated())

    static func loadGenerated() -> [ElevenLabsOperation] {
        guard let parsed = try? JSONSerialization.jsonObject(with: Data(generatedJSON.utf8)),
              case .array(let entries) = JSONValue(foundation: parsed)
        else { return [] }
        return entries.compactMap(operation(from:))
    }

    /// One generated entry, with the policy fields from the reviewed table.
    static func operation(from entry: JSONValue) -> ElevenLabsOperation? {
        guard let id = entry["id"].stringValue, let method = entry["method"].stringValue,
              let path = entry["path"].stringValue
        else { return nil }
        let parameters: [ElevenLabsParameter] = (entry["parameters"].arrayValue ?? []).compactMap {
            guard let name = $0["name"].stringValue,
                  let location = $0["location"].stringValue.flatMap(ElevenLabsParameter.Location.init)
            else { return nil }
            let fallback = $0["defaultValue"]
            return ElevenLabsParameter(
                name: name, location: location, required: $0["required"].boolValue ?? false,
                description: $0["description"].stringValue ?? "", schema: $0["schema"],
                defaultValue: $0.objectValue?["defaultValue"] == nil ? nil : fallback
            )
        }
        var body: ElevenLabsBody?
        if case .object = entry["body"],
           let contentType = entry["body"]["contentType"].stringValue.flatMap(ElevenLabsBody.ContentType.init) {
            body = ElevenLabsBody(
                contentType: contentType, required: entry["body"]["required"].boolValue ?? false,
                schema: entry["body"]["schema"],
                fileFields: entry["body"]["fileFields"].arrayValue?.compactMap(\.stringValue) ?? []
            )
        }
        let response: ElevenLabsResponseKind
        switch entry["response"]["kind"].stringValue {
        case "audio": response = .audio
        case "binary": response = .binary(entry["response"]["contentType"].stringValue ?? "application/octet-stream")
        case "text": response = .text
        case "events": response = .events
        case "multipartMixed": response = .multipartMixed
        default: response = .json
        }
        let risk = ElevenLabsRiskTable.risk(for: id, method: method, path: path)
        return ElevenLabsOperation(
            id: id, method: method, path: path, group: entry["group"].stringValue ?? "Other",
            summary: entry["summary"].stringValue ?? "", details: entry["details"].stringValue ?? "",
            deprecated: entry["deprecated"].boolValue ?? false, parameters: parameters, body: body,
            response: response, risk: risk,
            billable: ElevenLabsRiskTable.isBillable(id, risk: risk),
            returnsCredential: ElevenLabsRiskTable.returnsCredential(id),
            supportsStreaming: entry["supportsStreaming"].boolValue ?? false
        )
    }
}
